### ISSUE TITLE
Does not build with Swift 5.0 on Ubuntu 18.10

### ISSUE THREAD

**Issue by jgh-** [rhx/SwiftLibXML#3]
I'm looking at the issue now, here's the error:

```
/home/james/dev/proj/deps/SwiftGLib/.build/gir2swift/.build/checkouts/SwiftLibXML/Sources/SwiftLibXML/XMLAttribute.swift:14:12: error: no such module 'libxml2'
    import libxml2
           ^
```

It seems to involve this statement here:
```
#if swift(>=4.1)
    import libxml2
#else
    import CLibXML2
#endif
```
So I'm wondering if something relating to libxml2 was removed in swift 5, i'm trying to track it down now but if you're more familiar with the internals of the frameworks maybe you already know where to look.  I think an easy fix would be to just check that it's less than 5 but then I wonder if they've replaced libxml2 with something that would be better to use...

**Comment by jgh-** [comment]
Just quickly replacing libxml2 with CLibXML2 it looks like getting this running with Swift 5 may be a bigger job than simply getting that import statement right

**Comment by rhx** [comment]
Can you try again (just committed a fix to CLibXML2).  I just tested this and it works fine for me.

**Comment by mag911** [comment]
Confirmed as working with Swift 5 under Debian buster, however, only using ```swift build```. Using ```./build.sh``` throws an error ```error: unknown option -lxml2; use --help to list available options```

**Comment by mag911** [comment]
I can confirm that downstream of SwiftLibXML, gir2swift now successfully completes its build, as does SwiftHelloGTK. I'll be closing issue #2. Cheers.
